"""
generate_schema.py - derive a flat column schema from the T24 XML sample.

    python flatten/generate_schema.py

Reads:
    sample-data/account_xml_data_sample.xml   - which tags/positions actually occur
    sample-data/lookup_metadata.csv           - cN[/m] -> business name

Writes:
    flatten/column_map.json                   - tag+position -> column, for the consumer
    flatten/create_table.sql                  - CREATE TABLE DDL for RisingWave

Schema is derived from the SAMPLE, not from the full 289-row lookup, so the
table only carries columns that really occur. The trade-off is that a record
using a tag absent from the sample has nowhere to go - consume_to_risingwave.py
warns loudly rather than dropping such values silently. Re-run this script
against a richer sample to widen the schema.

Three distinct tag shapes come out of the T24 data, and each maps differently:

  1. scalar        c1 occurs once            -> customer
  2. c20 LOCAL.REF each position is its OWN   -> m=4  -> arabic_title
                   business field                m=32 -> nab_flag
  3. true array    c47 repeats the same field -> cap_date_cr_int_01 .. _23

Rule: if the lookup has an exact (field, position) row, that name wins (case 2).
Otherwise fall back to the field's base name, numbered when the field occurs
more than once in the sample (case 3) and bare when it occurs once (case 1).
"""

from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path

import pandas as pd

PROJECT_DIR = Path(__file__).resolve().parent.parent
SAMPLE_XML = PROJECT_DIR / "sample-data" / "account_xml_data_sample.xml"
LOOKUP_CSV = PROJECT_DIR / "sample-data" / "lookup_metadata.csv"
OUT_MAP = Path(__file__).resolve().parent / "column_map.json"
OUT_DDL = Path(__file__).resolve().parent / "create_table.sql"

TABLE_NAME = "t24_account_columns"

# <c8>EGP</c8>, <c20 m="2">x</c20>, <c100/>, <c20 m="32"></c20>
TAG_RE = re.compile(r'<(c\d+)(?:\s+m="(\d+)")?\s*(?:/>|>)')


def scan_sample_positions(xml_text: str) -> dict[str, set[int]]:
    """field -> set of positions actually seen. No m attribute means position 1.

    Positions are collected as a SET, not a max: c20's positions are sparse in
    real data (1,2,3,4,32 in the sample). Generating range(1, max+1) would
    invent 27 columns for m=5..31 that no record can ever fill.
    """
    seen: dict[str, set[int]] = defaultdict(set)
    for field, m_attr in TAG_RE.findall(xml_text):
        seen[field].add(int(m_attr) if m_attr else 1)
    return dict(seen)


def load_lookup(csv_path: Path) -> tuple[dict[tuple[str, int], str], dict[str, str]]:
    """Return (exact (field, position) -> name, field -> base name)."""
    frame = pd.read_csv(csv_path, dtype=str).fillna("")

    exact: dict[tuple[str, int], str] = {}
    base: dict[str, str] = {}

    for row in frame.itertuples(index=False):
        field = row.field_index.strip()
        name = row.resolved_name_en.strip()
        m_index = row.m_index.strip()

        if m_index:
            exact[(field, int(m_index))] = name
        else:
            base[field] = name

    return exact, base


def build_columns(
    positions: dict[str, set[int]],
    exact: dict[tuple[str, int], str],
    base: dict[str, str],
) -> tuple[dict[str, str], list[str]]:
    """Return (map of "field:position" -> column name, ordered column list)."""
    column_map: dict[str, str] = {}
    ordered: list[str] = []
    unresolved: list[str] = []

    for field in sorted(positions, key=lambda f: int(f[1:])):
        observed = sorted(positions[field])
        highest = max(observed)

        # only positions that really occur - never the gaps between them
        for position in observed:
            if (field, position) in exact:
                # c20-style: this exact position has its own business name
                column = exact[(field, position)]
            elif field in base:
                # numbered only when the field genuinely repeats
                column = f"{base[field]}_{position:02d}" if highest > 1 else base[field]
            else:
                unresolved.append(f"{field}[{position}]")
                continue

            key = f"{field}:{position}"
            column_map[key] = column
            ordered.append(column)

    if unresolved:
        print(f"  WARNING: {len(unresolved)} tag(s) had no lookup entry: {', '.join(unresolved)}")

    return column_map, ordered


def render_ddl(columns: list[str]) -> str:
    body = ",\n".join(f"    {name:<40} VARCHAR" for name in columns)
    return (
        f"-- Generated by flatten/generate_schema.py - do not edit by hand.\n"
        f"-- {len(columns) + 1} columns (recid + {len(columns)} flattened from XML).\n"
        f"--\n"
        f"-- A plain table, NOT Kafka-connected: consume_to_risingwave.py writes\n"
        f"-- into it directly. INSERT on an existing PK upserts in RisingWave, so\n"
        f"-- Debezium r/c/u all map to INSERT and d maps to DELETE.\n"
        f"DROP TABLE IF EXISTS {TABLE_NAME};\n\n"
        f"CREATE TABLE {TABLE_NAME} (\n"
        f"    {'recid':<40} VARCHAR,\n"
        f"{body},\n"
        f"    PRIMARY KEY (recid)\n"
        f");\n"
    )


def main() -> None:
    print(f"Reading sample : {SAMPLE_XML.relative_to(PROJECT_DIR)}")
    print(f"Reading lookup : {LOOKUP_CSV.relative_to(PROJECT_DIR)}")

    positions = scan_sample_positions(SAMPLE_XML.read_text(encoding="utf-8"))
    exact, base = load_lookup(LOOKUP_CSV)
    column_map, ordered = build_columns(positions, exact, base)

    repeated = {f: p for f, p in positions.items() if len(p) > 1}
    sparse = {f: p for f, p in repeated.items() if len(p) != max(p)}

    print()
    print(f"  distinct tags in sample : {len(positions)}")
    print(f"  repeating tags          : {len(repeated)} -> "
          f"{', '.join(f'{f}x{len(p)}' for f, p in sorted(repeated.items(), key=lambda kv: int(kv[0][1:])))}")
    for field, present in sorted(sparse.items(), key=lambda kv: int(kv[0][1:])):
        print(f"    {field} positions are sparse ({','.join(map(str, sorted(present)))}) - "
              f"{max(present) - len(present)} gap position(s) skipped, no phantom columns")
    print(f"  generated columns       : {len(ordered)} (+ recid)")

    OUT_MAP.write_text(
        json.dumps({"table": TABLE_NAME, "columns": ordered, "map": column_map}, indent=2),
        encoding="utf-8",
    )
    OUT_DDL.write_text(render_ddl(ordered), encoding="utf-8")

    print()
    print(f"  wrote {OUT_MAP.relative_to(PROJECT_DIR)}")
    print(f"  wrote {OUT_DDL.relative_to(PROJECT_DIR)}")


if __name__ == "__main__":
    main()
